{{- define "a.data" -}}

name: foo

selector:
  app: foo
  concern: test

containers_dict:
  b:
    name: b
    image: foo2

  a1: 
    name: a1
    image: foo3
  app: 
    name: app
    image: foo

    lifecycle:
      preStop:
        exec:
          command:
            - /bin/sh
            - /root/cmd-stop_workers.sh
  
terminationGracePeriodSeconds: 0


{{- end -}}

{{- define "a.data.override" }}

containers_dict:
  app:
    command: 
      - tail
      - -f
      - /dev/null

{{- end -}}


{{ include "ph.deployment.render" (include "ph.override" (list "a.data.override" . ) | fromYaml ) }}

