{{- define "a.service.data" -}}

name: a-{{ .Release.Name }}

selector: {{ .Values.deployment.selector | toYaml | nindent 2 }}

ports: {{ .Values.ports | toYaml | nindent 2 }}

{{- end -}}

{{ include "ph.service.render" (include "a.service.data" . | fromYaml ) }}

