---
# Source: a/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1

metadata:
  name: a-RELEASE-NAME
  labels:
  annotations:

spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: a
      concern: app
  template: 
    metadata:
      labels: 
        app: a
        concern: app
      annotations:
        a: "1"
        b: "foo"
    
    spec: 
      initContainers:
        
        - name: init-a
          image: "foo"
          imagePullPolicy: IfNotPresent
          
          command: 
            - "a"
            - "b"
          
          
          env: 
          
          
          
          envFrom: 
          
          ports: 
          
        
        
        
        
        
        
          volumeMounts: 
            
          resources: 
            requests: 
                {}
            limits: 
                {} 
          
        
          
      
      containers: 
        
        
          - name: a
            image: "foo"
            imagePullPolicy: IfNotPresent
            
            
            
            
            env: 
            
            - name: a
              value: "1"
            
            - name: b
              value: "2"
            
            
            
              
            - name: a
              valueFrom:
                secretKeyRef:
                  name: foo
                  key: A
              
            - name: b
              valueFrom:
                secretKeyRef:
                  name: foo
                  key: B
              
            
            envFrom: 
            
            - secretRef:
                name: foo
            
            
            ports: 
            
          
          
          
          
          
          
            volumeMounts: 
              
              - 
                mountPath: /mtn
                name: a0
              - 
                mountPath: /mtn
                name: a2
              - 
                mountPath: /mtn
                name: foo
              - 
                mountPath: /mtn
                name: foo2
            resources: 
              requests: 
                  {}
              limits: 
                  {} 
            readinessProbe: 
              httpGet:
                path: /ready
                port: 8080
          
            livenessProbe: 
              httpGet:
                path: /healthz
                port: 8080
      
      
      
      
      
      
      imagePullSecrets: 
        
      
      volumes: 
        
        - name: a0
          emptyDir: {}
        - name: a1
          emptyDir: {}
        - name: a2
          emptyDir: {}
        - name: foo
          emptyDir: {}
        - name: foo2
          emptyDir: {}
      
      
      automountServiceAccountToken: false
      
      
         
  
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
