{{- define "ph.cronjob.render" -}}

apiVersion: batch/v1beta1
kind: CronJob

{{ include "ph.meta.render" . }}

{{ $spec := include "ph.job_spec.render" . | fromYaml }}

spec:
  schedule: {{ required "A schedule is needed for a cronjob" .schedule }}

  suspend: {{ default false .suspend }}
  
  {{ if hasKey . "successfulJobsHistoryLimit" }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  {{ end }}
  
  {{ if hasKey . "failedJobsHistoryLimit" }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  {{ end }}

  {{ if hasKey . "startingDeadlineSeconds" }}
  startingDeadlineSeconds: {{ .startingDeadlineSeconds }}
  {{ end }}
  
  {{ if hasKey . "concurrencyPolicy" }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{ end }}
  
  jobTemplate: {{ $spec | toYaml | nindent 4 }}
      

{{- end -}}
