{{- define "ph.cronjob.version" }}

{{ $version := (default "1.20.0" .version) }}

{{- if semverCompare ">=1.21.0" $version -}}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end -}}

{{- end -}}

{{- define "ph.cronjob.render" -}}

{{ include "ph.cronjob.version" . }}
kind: CronJob

{{ include "ph.meta.render" . }}

{{ $spec := include "ph.job_spec.render" . | fromYaml }}

spec:
  schedule: {{ required "A schedule is needed for a cronjob" .schedule }}

  suspend: {{ default false .suspend }}
 
  {{ if hasKey . "timeZone" }}
  timeZone: {{ .timeZone }}
  {{ end }}

  {{ if hasKey . "successfulJobsHistoryLimit" }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  {{ end }}
  
  {{ if hasKey . "failedJobsHistoryLimit" }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  {{ end }}

  {{ if hasKey . "startingDeadlineSeconds" }}
  startingDeadlineSeconds: {{ .startingDeadlineSeconds }}
  {{ end }}
  
  {{ if hasKey . "concurrencyPolicy" }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{ end }}
  
  jobTemplate: {{ $spec | toYaml | nindent 4 }}
      

{{- end -}}
