

{{- define "ph.ingress_class.render" -}}

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ required "A name is needed for the IngressClass!" .name }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .isDefault | default false | quote }}
spec:
  controller: {{ required "An ingressController name is required" .ingressController }}
  parameters:
    kind: IngressParameters
    name: {{ .name }}
    {{- if hasKey . "namespace"  }}
    {{ $version := (default "1.20.0" .version) }}
    {{- if semverCompare ">=1.23.0" $version -}}
    scope: Namespace
    namespace: {{ .namespace }}
    {{ end }}
    {{ end }}

{{- end -}}
