{{- define "ph.statefulset.render" -}}
apiVersion: apps/v1
kind: StatefulSet
{{ include "ph.meta.render" . }}
{{ include "ph.statefulset.spec.render" . }}
{{- end -}}

{{- define "ph.statefulset.spec.render" -}}
spec:
  serviceName: {{ required "A .serviceName is required" .serviceName }}
  selector:
    matchLabels: {{ required "A .selector is required" .selector | toYaml | nindent 6 }}
  replicas: {{ (default 1 .replicas) }}
  template:
    labels: {{ required "A .labels is required" .labels | toYaml | nindent 6 }}
    spec: {{ include "ph.pod.render" . | nindent 6 }}
  volumeClaimTemplates: {{ .volumeClaimTemplates | toYaml | nindent 4 }}
{{- end -}}
