{{- define "ph.clusterrole.render" -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

{{ include "ph.meta.render" . }}

{{ $rules := required "A rules object is required" .rules }}

rules: {{ $rules | toYaml | nindent 2 }}

{{ with .aggregationRule }}
aggregationRule: {{ . | toYaml | nindent 2 }}
{{ end }}

{{- end -}}
