{{- define "ph.secret_tls.render" -}}

{{- $ctx := . }}

kind: Secret
apiVersion: v1
{{ include "ph.meta.render" . }}
type: kubernetes.io/tls
data:{{-  range $k, $v := .data }}
  {{- $_ := printf "Secret (%s) key %s lacks value"  $ctx.name $k }}
  {{ $k }}: {{ required $_ $v }}
  {{- end }}

{{- end -}}

