{{- define "ph.job.render" -}}

kind: Job
apiVersion: batch/v1

{{ include "ph.meta.render" . }}

{{ include "ph.job_spec.render" . }}

{{- end -}}

{{- define "ph.job_spec.render" -}}

{{ $spec := include "ph.pod.render" . | fromYaml }}

{{ $_ := set $spec "restartPolicy" "Never" }}

spec:
  template: 
    metadata:
      {{ with .pod_labels }}
      labels: {{ . | toYaml | nindent 8 }}
      {{ end }}
      {{ with .pod_annotations }}
      annotations: {{ . | toYaml | nindent 8 }}
      {{ end }}

    spec: {{ $spec | toYaml | nindent 6 }}
    
  {{ if hasKey . "activeDeadlineSeconds" }}
  activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
  {{ end }}

  {{ if hasKey . "backoffLimit" }}
  backoffLimit: {{ .backoffLimit }}
  {{ end }}

  {{ if hasKey . "completionMode" }}
  completionMode: {{ .completionMode }}
  {{ end }}
  
  {{ if hasKey . "manualSelector" }}
  manualSelector: {{ .manualSelector }}
  {{ end }}

  {{ if hasKey . "parallelism" }}
  parallelism: {{ .parallelism }}
  {{ end }}

  {{ if hasKey . "selector" }}
  selector: {{ .selector | toYaml | nindent 4 }}
  {{ end }}

  {{ if hasKey . "ttlSecondsAfterFinished" }}
  ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished }}
  {{ end }}

{{- end -}}
