{{- define "ph.role.render" -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role

{{ include "ph.meta.render" . }}

{{ $rules := required "A rules object is required" .rules }}

rules: {{ $rules | toYaml | nindent 2 }}

{{- end -}}
