{{- define "ph.secret.render" -}}

{{- $ctx := . }}

kind: Secret
apiVersion: v1

{{ include "ph.meta.render" . }}

type: {{ default "Opaque" .type }}

data:{{-  range $k, $v := .data }}
  {{- $_ := printf "Secret (%s) key %s lacks value"  $ctx.name $k }}
  {{ $k }}: {{ required $_ $v | b64enc}}
  {{- end }}

{{- end -}}

{{- define "ph.secret.render.@tls" -}}

type: kubernetes.io/tls

{{- end -}}

{{- define "ph.secret_tls.render" -}}

{{ include "ph.override" (list "ph.secret.render.@tls" . ) }}

{{- end -}}
