{{- define "ph.sa.render" -}}

apiVersion: v1
kind: ServiceAccount
{{ include "ph.meta.render" . }}

{{ if hasKey . "automountServiceAccountToken" -}}
automountServiceAccountToken: {{ .automountServiceAccountToken }}
{{ else -}}
automountServiceAccountToken: true
{{- end -}}

{{- with .secrets -}}
secrets:
{{ range $s := . }}
  - name: {{ $s }}
{{ end }}
{{- end -}}

{{- with .imagePullSecrets -}}
imagePullSecrets:
{{ range $s := . }}
  - name: {{ $s }}
{{ end }}
{{- end -}}

{{- end -}}
