name: release-pipeline

on:
  release:
    types: [released]

jobs:
  pipeline:
    env:
      repositorio: prefapp-helm
      proyecto: prefapp
      git_user: 'github-actions'
      git_email: 'github-actions@github.com'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculating branch name
        id: step-branch
        run: echo "::set-output name=branch::$(echo new-release/${{ github.event.release.tag_name }})"

      - name: Commit Message
        id: step-commit_message
        run: echo "::set-output name=commit_message::$(echo New Chart Release '${{ github.event.release.tag_name }}')"

      - name: Create branch with changes
        run: |
          git config --global user.name ${{ env.git_user }}
          git config --global user.email ${{ env.git_email }}
          git checkout -b ${{ steps.step-branch.outputs.branch }}
          helm package . -d docs/
          cd docs/ && helm repo index . 
          git add .
          git commit -m "${{steps.step-commit_message.outputs.commit_message}}"
          git push origin ${{ steps.step-branch.outputs.branch }}

      - name: Create Pull Request
        run: |
          prName="Bump release ${{ github.event.release.tag_name }}"
          docker run -v $(pwd):/repo prefapp/prefapp-cicdpy:sleep-test github.pr_auto_merge \
             token=${{ secrets.GITHUB_TOKEN }} \
             titulo="${prName}" \
             rama_origen=${{ steps.step-branch.outputs.branch }} \
             repo=${{ env.repositorio }} \
             proyecto=${{ env.proyecto }} \
             reviewers='${{ github.actor }}'
