on:
  push:
    branches:
      - master
name: Run Release Please
jobs:
  release-please:
    name: Release Please Manifest
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
      releases_info: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: master

      - run: echo $JSON
        name: Release Please Output Info
        env:
          JSON: ${{ toJSON(steps.release.outputs) }}

  packages-publish:
    if: needs.release-please.outputs.paths_released != '[]'
    needs:
      - release-please
    name: Charts Packages Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{fromJson(needs.packages-calculate.outputs.result)}}
    steps:
    - name: Workflow publish
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
       curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        https://api.github.com/repos/prefapp-helm/actions/workflows/publish-chart.yaml/dispatches \
        -d '{"ref":"master","inputs":{"package":"prefapp-helm","version":"v${{needs.release-please.outputs.releases_info.version}}"}}'
